//
//  Program.swift
//  SummerPrograms
//
//  Created by Manan Agarwal on 11/03/22.
//

import Foundation

struct Program: Identifiable {
    
    let id: UUID
    var name: String
    var website: String
    var location: [String]
    var country: Country
    var site: Site
    var creditsGiven: Bool
    var length: Int
    var date: Date
    var grade: [Int]
    var internationalAllowed: Bool
    var cost: Int
    var needBasedAid: Bool
    var Subject: Subject
    var selectivity: Bool
    var entranceTest: Bool
    var entranceRequirements: [Bool]
    var thresholdSAT: Int
    var thresholdGPA: Double
    var description: String
    var featured: Bool
    
    init(id: UUID=UUID(), name: String, website: String, location: [String], country: Country, site: Site, creditsGiven: Bool, length: Int, date: Date, grade: [Int], internationalAllowed: Bool, cost: Int, needBasedAid: Bool, Subject: Subject, selectivity: Bool, entranceTest: Bool, entranceRequirements: [Bool], thresholdSAT: Int, thresholdGPA: Double, description: String, featured: Bool) {
        self.id = id
        self.name = name
        self.website = website
        self.location = location
        self.country = country
        self.site = site
        self.creditsGiven = creditsGiven
        self.length = length
        self.date = date
        self.grade = grade
        self.internationalAllowed = internationalAllowed
        self.cost = cost
        self.needBasedAid = needBasedAid
        self.Subject = Subject
        self.selectivity = selectivity
        self.entranceTest = entranceTest
        self.entranceRequirements = entranceRequirements
        self.thresholdSAT = thresholdSAT
        self.thresholdGPA = thresholdGPA
        self.description = description
        self.featured = featured
    }
    
    
}

extension Program {
    
    var weightages: [Double] {
        var x: [Double] = []
        for val in entranceRequirements {
            if (val) {
                x.append(1)
            }
            else {
                x.append(0)
            }
        }
        let sum: Double = x.reduce(0, +)
        return x.map {$0 / sum}
    }
    
    struct Date {
        let start_day: Int
        let start_month: Int
        let end_day: Int
        let end_month: Int
        init(start_day: Int, start_month: Int, end_day: Int, end_month: Int) {
            self.start_day = start_day
            self.start_month = start_month
            self.end_day = end_day
            self.end_month = end_month
        }
    }
    
    struct Subject {
        let engineering: Bool
        let physical_sciences: Bool
        let mathematics: Bool
        let computer_science: Bool
        init (engineering: Bool, physical_sciences: Bool, mathematics: Bool, computer_science: Bool) {
            self.engineering = engineering
            self.physical_sciences = physical_sciences
            self.mathematics = mathematics
            self.computer_science = computer_science
        }
    }
    
//    struct entranceRequirements {
//        let entranceTest: Bool
//        let reco: Bool
//        let standardised_test: Bool
//        let transcript: Bool
//        let math_exams: Bool
//        let science_exams: Bool
//        let project: Bool
//        let research: Bool
//        let eca: Bool
//        let CGPA: Double
//        let SAT: Int
//        let ACT: Int
//        let PSAT: Int
//        init (entranceTest: Bool, reco: Bool, standardised_test: Bool, transcript: Bool, math_exams: Bool, science_exams: Bool, project: Bool, research: Bool, eca: Bool, CGPA: Double, SAT: Int, ACT: Int, PSAT: Int) {
//            self.entranceTest = entranceTest
//            self.reco = reco
//            self.standardised_test = standardised_test
//            self.transcript = transcript
//            self.math_exams = math_exams
//            self.science_exams = science_exams
//            self.project = project
//            self.research = research
//            self.eca = eca
//            self.CGPA = CGPA
//            self.SAT = SAT
//            self.ACT = ACT
//            self.PSAT = PSAT
//        }
//    }
}

extension Program {
    static let programs: [Program] =
        [
            Program(name: "Michigan Math and Science Scholars", website: "sites.lsa.umich.edu/mmss/", location: ["College of Literature, Science & Arts, University of Michigan Ann-Arbor"], country: Country.US, site: Site.Residential, creditsGiven: false, length: 2, date: Date(start_day: 26, start_month: 6, end_day: 8, end_month: 7), grade: [9, 10, 11], internationalAllowed: true, cost: 2300, needBasedAid: true, Subject: Subject(engineering: false, physical_sciences: true, mathematics: true, computer_science: true), selectivity: true, entranceTest: false, entranceRequirements: [true, true, true, false, false, false, false, true], thresholdSAT: 1500, thresholdGPA: 3.5, description: "The Michigan Math and Science Scholars program is designed to offer a pre-college experience exposing students to a breadth of curricula offered at the University of Michigan while introducing high school students to current developments and research in the sciences. The program is open to any high school rising sophomore, junior or, senior from around the world. Three 2-week sessions are offered; students are given the opportunity to attend one, two or all three sessions. MMSS features small 15-student classes taught by University of Michigan faculty. Students take only one class per session and spend the majority of the day working with their class.", featured: false),
            Program(name: "Canada / USA Mathcamp", website: "mathcamp.org", location: ["Colby Collge, Waterville"], country: Country.US, site: Site.Residential, creditsGiven: false, length: 5, date: Date(start_day: 3, start_month: 7, end_day: 7, end_month: 8), grade: [9, 10, 11, 12], internationalAllowed: true, cost: 4500, needBasedAid: true, Subject: Subject(engineering: false, physical_sciences: false, mathematics: true, computer_science: false), selectivity: true, entranceTest: true, entranceRequirements: [true, false, false, true, false, false, false, false], thresholdSAT: 1500, thresholdGPA: 3.5, description: "Canada/USA Mathcamp is an intensive 5-week-long summer program for about 120 mathematically talented high school students, designed to expose these students to the beauty of advanced mathematical ideas and to new ways of thinking. More than just a summer camp, Mathcamp is a vibrant community, made up of a wide variety of people who share a common love of learning and passion for mathematics. At Mathcamp, students can explore undergraduate and even graduate-level topics while building problem-solving skills that will help them in any field they choose to study. Mathcamp is held on a different campus each year and lasts for five weeks. In 2022, Mathcamp will take place at Colby College in Waterville, ME from Sunday, July 3 to Sunday, August 7.", featured: false),
            Program(name: "Research Science Institute (organized by Center for Excellence in Education)", website: "cee.org/programs/research-science-institute", location: ["Massachussets Institute of Technology"], country: Country.US, site: Site.Residential, creditsGiven: false, length: 6, date: Date(start_day: 23, start_month: 6, end_day: 2, end_month: 8), grade: [11], internationalAllowed: true, cost: 0, needBasedAid: false, Subject: Subject(engineering: true, physical_sciences: true, mathematics: false, computer_science: false), selectivity: true, entranceTest: false, entranceRequirements: [true, true, true, true, true, true, true, false], thresholdSAT: 1500, thresholdGPA: 3.5, description: "Each summer, 80 of the world's most accomplished high school students gather at the Massachusetts Institute of Technology (MIT) for the Research Science Institute (RSI). RSI is the first cost-free to students, summer science & engineering program to combine on-campus course work in scientific theory with off-campus work in science and technology research. Participants experience the entire research cycle from start to finish. They read the most current literature in their field, draft and execute a detailed research plan, and deliver conference-style oral and written reports on their findings. RSI scholars first participate in a week of intensive STEM classes with accomplished professors. The heart of RSI is the five week research internship where students conduct individual projects under the tutelage of mentors who are experienced scientists and researchers. During the final week of RSI, students prepare written and oral presentations on their research projects.", featured: true),
            Program(name: "Hampshire College Summer Studies in Mathematics", website: "hcssim.org", location: ["Hampshire College, Massachussets"], country: Country.US, site: Site.Residential, creditsGiven: false, length: 6, date: Date(start_day: 3, start_month: 7, end_day: 12, end_month: 8), grade: [9, 10, 11], internationalAllowed: true, cost: 4913, needBasedAid: true, Subject: Subject(engineering: false, physical_sciences: false, mathematics: true, computer_science: false), selectivity: true, entranceTest: true, entranceRequirements: [true, false, false, true, false, false, false, false], thresholdSAT: 1500, thresholdGPA: 3.5, description: "HCSSiM is an intensive six-week encounter with college-level mathematics for talented and highly motivated high school students. It is demanding and expanding. Participants spend a major portion of each day actively engaged in doing mathematics (not simply learning the results of mathematics). Initially, Summer Studies participants will be partitioned into workshops, each led by a college or university professor and one or two graduate or undergraduate students. Each workshop will actively and intensively investigate problems from many areas of mathematics, with emphasis on unifying themes, recurrent patterns, and fruitful modes of inquiry. Midway through the session, students and staff will regroup into “maxi-courses” and “mini-courses” for in-depth studies of particular problems and fields. Students will be able to select topics such as combinatorics, number theory, complex numbers, probability, four-dimensional geometry, fractals and chaos, graph theory, topology, and cellular automata.", featured: false),
            Program(name: "Stanford University Mathematics Camp", website: "sumac.spcs.stanford.edu", location: ["Stanford University"], country: Country.US, site: Site.Online, creditsGiven: false, length: 3, date: Date(start_day: 20, start_month: 6, end_day: 8, end_month: 7), grade: [10, 11], internationalAllowed: true, cost: 3250, needBasedAid: true, Subject: Subject(engineering: false, physical_sciences: false, mathematics: true, computer_science: false), selectivity: true, entranceTest: false, entranceRequirements: [true, true, true, true, false, false, true, false], thresholdSAT: 1500, thresholdGPA: 3.5, description: "In this three-week online program, rising high school juniors and seniors engage in deep exploration of mathematics and develop as mathematicians. SuMaC offers two courses with unique topics for each course. Each student attends one of two courses, both of which build on topics central to mathematics through their historical significance and their relevance to current lines of mathematical research. The SUMaC courses focus on pure mathematics—that is, mathematics that is motivated independently of ties to other sciences", featured: true),
            Program(name: "Stanford Pre-Collegiate Summer Institutes", website: "spcs.stanford.edu/programs/stanford-pre-college-summer-institutes", location: ["Stanford University"], country: Country.US, site: Site.Online, creditsGiven: false, length: 2, date: Date(start_day: 20, start_month: 6, end_day: 1, end_month: 7), grade: [8, 9, 10, 11], internationalAllowed: true, cost: 2700, needBasedAid: true, Subject: Subject(engineering: true, physical_sciences: true, mathematics: true, computer_science: true), selectivity: true, entranceTest: false, entranceRequirements: [true, false, true, false, false, true, false, true], thresholdSAT: 1500, thresholdGPA: 3.5, description: "Stanford Pre-Collegiate Summer Institutes is an online summer program where participants engage in single-subject intensive study and benefit from small class sizes and academically motivated peers. Courses are offered in a range of subject areas, including Business, Bioscience, Computer Science, Creative Writing, Engineering, Math, Philosophy, Physics, and more. Each course is customized by its instructors to give students deep exposure and hands-on experience. Academics and social activities are integrated into every aspect of our program. ", featured: true),
            Program(name: "Belin-Blank Center - Secondary Student Training Program", website: "belinblank.education.uiowa.edu/students/sstp/", location: ["Iowa University"], country: Country.US, site: Site.Both, creditsGiven: true, length: 6, date: Date(start_day: 22, start_month: 6, end_day: 29, end_month: 7), grade: [9, 10], internationalAllowed: true, cost: 7500, needBasedAid: true, Subject: Subject(engineering: true, physical_sciences: true, mathematics: true, computer_science: false), selectivity: true, entranceTest: false, entranceRequirements: [true, false, true, false, true, true, true, false], thresholdSAT: 1500, thresholdGPA: 3.5, description: "Secondary Student Training Program (SSTP) is a highly selective and intensive summer research program that offers rare access to elite opportunities that help realize academic and professional goals. You will conduct research under the mentorship of world-class faculty from a research-intensive university. Participate in classes and events that will stretch you as a researcher and scholar. ", featured: false),
            Program(name: "Program in Mathematics for Young Scientists (PROMYS)", website: "promys.org", location: ["Boston University"], country: Country.US, site: Site.Residential, creditsGiven: false, length: 6, date: Date(start_day: 3, start_month: 7, end_day: 13, end_month: 8), grade: [9, 10, 11, 12], internationalAllowed: true, cost: 5500, needBasedAid: true, Subject: Subject(engineering: false, physical_sciences: false, mathematics: true, computer_science: false), selectivity: true, entranceTest: true, entranceRequirements: [true, false, true, true, false, false, true, false], thresholdSAT: 1500, thresholdGPA: 3.5, description: "PROMYS is a six-week summer program in mathematics for strongly motivated high school students who are carefully selected from across the U.S. and around the world. Founded in 1989, PROMYS is a residential program held on the campus of Boston University with approximately 80 high school students and 25 undergraduate counselors. Over six immersive weeks, participants practice the art of discovery through their intensive efforts to prove fundamental mathematical ideas.", featured: true),
            Program(name: "Ross Mathematics Program", website: "rossprogram.org", location: ["Ohio Dominican University", "Rose-Hulman Institute of Technology"], country: Country.US, site: Site.Residential, creditsGiven: false, length: 6, date: Date(start_day: 15, start_month: 6, end_day: 27, end_month: 7), grade: [9, 10, 11, 12], internationalAllowed: true, cost: 6000, needBasedAid: true, Subject: Subject(engineering: false, physical_sciences: false, mathematics: true, computer_science: false), selectivity: true, entranceTest: true, entranceRequirements: [true, false, true, true, false, false, true, false], thresholdSAT: 1500, thresholdGPA: 3.5, description: "Ross is a six-week, residential, summer session for high school students who are talented in mathematics, well prepared in standard high school math topics, and eager to explore more advanced ideas. Ross participants spend most of each day working on challenging sets of problems dealing with abstract mathematical concepts. By working for several weeks on one subject (number theory), participants delve deeply into the underpinnings of that subject. But more importantly, they learn to communicate mathematical ideas clearly and to write convincing proofs of all of their assertions. One goal of this program is to provide a first step toward independent mathematical research. It is not oriented toward math contests. ", featured: true),
            Program(name: "Honours Summer Maths Camp", website: "txstate.edu/mathworks/camps/Summer-Math-Camps-Information/hsmc.html", location: ["Texas State University"], country: Country.US, site: Site.Residential, creditsGiven: false, length: 6, date: Date(start_day: 19, start_month: 6, end_day: 30, end_month: 7), grade: [8, 9, 10, 11], internationalAllowed: true, cost: 4800, needBasedAid: true, Subject: Subject(engineering: false, physical_sciences: false, mathematics: true, computer_science: false), selectivity: true, entranceTest: false, entranceRequirements: [false, false, true, true, false, false, true, false], thresholdSAT: 1500, thresholdGPA: 3.5, description: "The Mathworks Honors Summer Math Camp (HSMC) is an intensive multi-summer program for high school students. The goal of the program is to develop talented students of all socioeconomic backgrounds through immersive and in-depth experiences in a unique learning environment.  Students develop important skills for future degrees and careers in math, science, engineering, and many other fields. Each summer, HSMC is a six-week, residential camp. ", featured: false),
            Program(name: "MathILy and MathILY Er", website: "mathily.org", location: ["2022 location to be determined"], country: Country.US, site: Site.Residential, creditsGiven: false, length: 5, date: Date(start_day: 1, start_month: 7, end_day: 31, end_month: 7), grade: [8, 9, 10, 11], internationalAllowed: true, cost: 4950, needBasedAid: true, Subject: Subject(engineering: false, physical_sciences: false, mathematics: true, computer_science: false), selectivity: true, entranceTest: true, entranceRequirements: [true, false, false, true, false, false, false, false], thresholdSAT: 1500, thresholdGPA: 3.5, description: "MathILY and MathILy-Er are intensive residential summer programs for mathematically excellent secondary students. In MathILy classes, instructors provide the framework and you get to make (and prove!) the conjectures. You will encounter new ideas, improve your problem-solving skills, learn lots and lots of advanced mathematics, and hone your overall thinking skills. MathILy-Er is similar to MathILy but is adapted for students who are slightly earlier in their chronology or mathematical development. The mathematical content is distinct so that you can participate in both programs effectively in different years. Mathematical content is undergraduate- and graduate-level mathematics not usually encountered in high school. The core of the curriculum is discrete mathematics, with additional material determined partly by the interests and direction of the class. Topics include combinatorics, graph theory, affine geometry, and theoretical linear algebra, and are likely to include some proof techniques, number theory, probability, group theory, and cardinality. ", featured: false),
            Program(name: "John Hopkins Explore Engineering Innovation", website: "ei.jhu.edu", location: ["John Hopkins University (multiple locations)"], country: Country.US, site: Site.Both, creditsGiven: true, length: 4, date: Date(start_day: 27, start_month: 6, end_day: 29, end_month: 7), grade: [10, 11], internationalAllowed: true, cost: 8215, needBasedAid: true, Subject: Subject(engineering: true, physical_sciences: true, mathematics: true, computer_science: false), selectivity: true, entranceTest: false, entranceRequirements: [true, true, true, false, true, false, false, true], thresholdSAT: 1500, thresholdGPA: 3.5, description: "Explore Engineering Innovation (EEI), formerly called Engineering Innovation, is an exciting, college-level, summer program for motivated high school students with an aptitude in math and science and an interest in (or curiosity about) engineering.  Students complete hands-on projects in a variety of engineering disciplines (civil, electrical/computer, chemical, materials, and mechanical) and learn to think and problem-solve like engineers. Participating students have the opportunity to earn Johns Hopkins University (JHU) credit.  By applying their knowledge of math and science to labs and hands-on projects, the concepts they’ve learned in their high school classrooms are linked to real-world practice.  Additionally, their confidence grows as they attend college-level lectures, solve problems, test theories and ultimately learn to think like engineers.  ", featured: true),
            Program(name: "Engineering Summer Academy at Penn", website: "esap.seas.upenn.edu", location: ["Pennsylvania University"], country: Country.US, site: Site.Residential, creditsGiven: true, length: 3, date: Date(start_day: 10, start_month: 7, end_day: 30, end_month: 7), grade: [9, 10, 11], internationalAllowed: true, cost: 7635, needBasedAid: true, Subject: Subject(engineering: true, physical_sciences: true, mathematics: false, computer_science: true), selectivity: true, entranceTest: false, entranceRequirements: [true, true, true, true, true, true, false, true], thresholdSAT: 1500, thresholdGPA: 3.5, description: "The Engineering Summer Academy at Penn (ESAP) welcomes highly motivated and talented students to explore Engineering at the college level.  The Academy’s intensive, three-week programs combine sophisticated theory with hands-on practical experience in cutting edge technologies. Work with leading faculty while earning college credit, live on Penn’s historic campus, and connect with new friends from around the world.", featured: false),
            Program(name: "California State Summer School for Mathematics and Science (COSMOS)", website: "cosmos-ucop.ucdavis.edu, cosmos.ucdavis.edu, cosmos.uci.edu, cosmos.ucsc.edu", location: ["UC Davis, UC Irvine, UC San Diego and UC Santa Cruz"], country: Country.US, site: Site.Residential, creditsGiven: false, length: 4, date: Date(start_day: 10, start_month: 7, end_day: 6, end_month: 8), grade: [8, 9, 10, 11], internationalAllowed: true, cost: 4550, needBasedAid: true, Subject: Subject(engineering: true, physical_sciences: true, mathematics: true, computer_science: true), selectivity: true, entranceTest: false, entranceRequirements: [true, false, true, true, true, false, false, true], thresholdSAT: 1500, thresholdGPA: 3.5, description: "COSMOS is an intensive four-week summer residential program for students who have demonstrated an aptitude for academic and professional careers in science, technology, engineering and mathematics (STEM) subjects. Talented and motivated students completing grades 8-12 have the opportunity to be mentored by renowned faculty, researchers and scientists in state-of-the-art facilities, while exploring advanced STEM topics far beyond the courses usually offered in California high schools. Through challenging curricula that are both hands-on and lab intensive, COSMOS fosters its students’ interests, skills, and awareness of educational and career options in STEM fields. Students apply to one of the four University of California’s COSMOS campuses — UC Davis, UC Irvine, UC San Diego and UC Santa Cruz. Each campus can only accommodate about 160-200 participants, so selection is competitive. ", featured: false),
            Program(name: "Yale Young Global Scholars", website: "globalscholars.yale.edu", location: ["Yale University"], country: Country.US, site: Site.Online, creditsGiven: false, length: 2, date: Date(start_day: 21, start_month: 6, end_day: 3, end_month: 7), grade: [10, 11], internationalAllowed: true, cost: 3500, needBasedAid: true, Subject: Subject(engineering: true, physical_sciences: true, mathematics: false, computer_science: false), selectivity: true, entranceTest: false, entranceRequirements: [true, false, true, false, true, true, false, true], thresholdSAT: 1500, thresholdGPA: 3.5, description: "Yale Young Global Scholars (YYGS) is an academic enrichment program for outstanding high school students from around the world. Each summer, students from over 150 countries participate in one interdisciplinary, two-week session online or at Yale’s historic campus. Yale Young Global Scholars emphasizes an open, exploratory, and collaborative approach to learning and is designed to allow students to experience learning in a variety of different university contexts, from large lectures to small seminars, and working with different group of peers and learning contexts, which allows for a wide range of peer-to-peer interaction.", featured: true),
            Program(name: "Awesome Math Summer Program", website: "awesomemath.org", location: ["Multiple locations"], country: Country.US, site: Site.Online, creditsGiven: false, length: 3, date: Date(start_day: 6, start_month: 6, end_day: 24, end_month: 6), grade: [8, 9, 10, 11], internationalAllowed: true, cost: 1990, needBasedAid: false, Subject: Subject(engineering: false, physical_sciences: false, mathematics: true, computer_science: false), selectivity: true, entranceTest: true, entranceRequirements: [true, false, false, true, false, false, false, false], thresholdSAT: 1500, thresholdGPA: 3.5, description: "The AwesomeMath Summer Program is an intensive three-week online program for is designed for bright middle and high school students from around the globe who wish to sharpen their problem-solving skills and further their mathematics education. Many of the participants seek to improve their performance on contests such as AMC10/12, AIME, or USAMO. Students can enrol in one or more sessions and there is no limit on maximum or minimum number of courses within a session. The course category includes algebra, combinatorics, geometry and number theory.", featured: true),
            Program(name: "Student Science Training Program", website: "cpet.ufl.edu/students/uf-cpet-summer-programs/student-science-training-program/", location: ["University of Florida"], country: Country.US, site: Site.Both, creditsGiven: true, length: 6, date: Date(start_day: 12, start_month: 6, end_day: 29, end_month: 7), grade: [11], internationalAllowed: true, cost: 4800, needBasedAid: true, Subject: Subject(engineering: true, physical_sciences: true, mathematics: false, computer_science: false), selectivity: true, entranceTest: false, entranceRequirements: [true, true, true, true, true, true, true, true], thresholdSAT: 1500, thresholdGPA: 3.5, description: "The University of Florida Student Science Training Program (UF SSTP) is a six week blended (online and residential) research program for selected students entering senior year and at least 16 years old by the program start date who are considering science, medicine, math, computer science, or engineering careers. The program emphasis is research participation with a UF faculty research scientist and his or her research team. Students interested in attending the UF SSTP must possess a high level of maturity, an ability to live and learn independently, a desire to work collaboratively, and a sincere interest in research. Students engage in the ongoing research of the faculty-mentor for 30 hours each week, attend a daily lecture series on current research topics, and participate in a UF honors seminar class.  Additionally, students develop important interpersonal, leadership, professional communication, and organizational skills through academic, social, and service activities.  Students enrolled in a Florida high school have the option to earn dual enrollment credit.", featured: false),
            Program(name: "International Summer School for Young Physicists", website: "perimeterinstitute.ca/issyp", location: ["Perimeter Institute for Theoretical Physics"], country: Country.Canada, site: Site.Online, creditsGiven: false, length: 2, date: Date(start_day: 18, start_month: 7, end_day: 29, end_month: 7), grade: [11, 12], internationalAllowed: true, cost: 200, needBasedAid: true, Subject: Subject(engineering: false, physical_sciences: true, mathematics: false, computer_science: false), selectivity: true, entranceTest: false, entranceRequirements: [true, false, true, false, false, true, false, true], thresholdSAT: 1500, thresholdGPA: 3.5, description: "The International Summer School for Young Physicists (ISSYP) is an opportunity for Canadian and international high school students to focus on theoretical physics and physics studies for two weeks. The International Summer School for Young Physicists (ISSYP) has been around for 18 years and has produced over 800 alum from 60 countries. The International Summer School for Young Physicists provides a brief college-level experience, from the intense studying and working to living on a university campus, high school students get a taste of college and university life while creating friendships and diving into physics with top scientists.Students will be able to hear from  Perimeter scientists and be mentored by physicists, to learn about the career path offers, to listen to important presentations, and more.", featured: true),
            Program(name: "Summer Science Program", website: "summerscience.org", location: ["UNC Chapel Hill, University of Colorado, New Mexico Institute of Mining and Technology, Indiana University, Purdue University"], country: Country.US, site: Site.Residential, creditsGiven: false, length: 6, date: Date(start_day: 12, start_month: 6, end_day: 20, end_month: 7), grade: [10, 11], internationalAllowed: true, cost: 7950, needBasedAid: true, Subject: Subject(engineering: false, physical_sciences: true, mathematics: false, computer_science: false), selectivity: true, entranceTest: false, entranceRequirements: [true, false, true, true, true, true, true, false], thresholdSAT: 1500, thresholdGPA: 3.5, description: "The Summer Science Program offers teens an exhilarating and inspiring immersion into hands-on experimental science. Working in teams of three, 36 participants and 7 faculty form a supportive “living and learning community” over 39 days. Each team completes a real research project, taking and analyzing original data. Afterward, they join a worldwide network of 2,500+ alumni of all ages. In 2022 we will operate six programs, namely, three in astrophysics, two in biochemistry and one in genomics. ", featured: false),
            Program(name: "Clark Scholars Program", website: "depts.ttu.edu/honors/academicsandenrichment/affiliatedandhigh school/clark", location: ["Texas Tech University"], country: Country.US, site: Site.Residential, creditsGiven: false, length: 7, date: Date(start_day: 20, start_month: 6, end_day: 3, end_month: 8), grade: [11, 12], internationalAllowed: true, cost: 0, needBasedAid: false, Subject: Subject(engineering: true, physical_sciences: true, mathematics: true, computer_science: true), selectivity: true, entranceTest: false, entranceRequirements: [true, true, true, false, false, true, true, true], thresholdSAT: 1500, thresholdGPA: 3.5, description: "The Clark Scholar Program is an intensive seven week summer research program for highly qualified high school juniors and seniors. The Program at Texas Tech University helps the Scholars to have a hands-on practical research experience with outstanding and experienced faculty. This Program provides opportunities for research in all academic areas in the university. The Program includes fun activities, weekly seminars and field trips. The Scholars will receive a  $750 tax-free stipend and room and board. ", featured: false),
            Program(name: "Centre for Academically Talented Youth - Accelerated Learning Program", website: "precollege.wisc.edu/alp/", location: ["University of Wisconsin - Madison"], country: Country.US, site: Site.Residential, creditsGiven: true, length: 3, date: Date(start_day: 3, start_month: 7, end_day: 23, end_month: 7), grade: [9, 10, 11, 12], internationalAllowed: true, cost: 4400, needBasedAid: true, Subject: Subject(engineering: true, physical_sciences: true, mathematics: false, computer_science: true), selectivity: true, entranceTest: false, entranceRequirements: [false, false, true, false, false, true, false, true], thresholdSAT: 1500, thresholdGPA: 3.5, description: "The Accelerated Learning Program (ALP) engages talented students from across the world at the University of Wisconsin–Madison. ALP is an intense, three-week residential summer camp designed to push students to the next academic level in a welcoming learning environment. Students enroll in a single course for an in-depth experience and may work with their school to receive high school credit. Classes are small (no more than 16 students) to allow meaningful mentoring and personal relationships between students and their instructor. Instructors work individually with each student to identify learning goals and ensure that coursework is challenging but not overwhelming.", featured: false),
            Program(name: "Summer college Immersion program", website: "summer.ucla.edu/summer-programs/summer-college-immersion-program", location: ["University of California - Los Angeles"], country: Country.US, site: Site.Both, creditsGiven: true, length: 6, date: Date(start_day: 20, start_month: 6, end_day: 29, end_month: 7), grade: [10, 11], internationalAllowed: true, cost: 4891, needBasedAid: true, Subject: Subject(engineering: true, physical_sciences: true, mathematics: true, computer_science: false), selectivity: true, entranceTest: false, entranceRequirements: [false, false, true, true, true, true, false, true], thresholdSAT: 1500, thresholdGPA: 3.5, description: "The UCLA Summer College Immersion Program (SCIP) offers exceptional high school students the opportunity to experience a comprehensive introduction to college life while studying alongside UCLA undergraduates. Designed to emulate the undergraduate experience, SCIP provides students access to a broad range of UCLA’s academic expertise and resources through lectures, workshops, and seminars, as well as UCLA coursework. SCIP’s co-curricular components are specifically curated to empower students to gain balance and thrive as they embark on their college journey.", featured: false),
            Program(name: "Garcia Research Scholar Program", website: "stonybrook.edu/commcms/garcia/summer_program", location: ["Stony Brooks University"], country: Country.US, site: Site.Residential, creditsGiven: false, length: 7, date: Date(start_day: 27, start_month: 6, end_day: 12, end_month: 8), grade: [12], internationalAllowed: true, cost: 3000, needBasedAid: false, Subject: Subject(engineering: true, physical_sciences: true, mathematics: false, computer_science: false), selectivity: true, entranceTest: false, entranceRequirements: [true, true, true, false, true, true, true, true], thresholdSAT: 1500, thresholdGPA: 3.5, description: "This is an intensive seven week program for gifted high school students which combines formal instruction with independent research and allows students to design original research projects with guidance from Garcia Center faculty, students, and staff. This Program offers the opportunity for high school teachers and students to perform research on the forefronts of polymer science and technology together with Garcia faculty and staff. Students work as part of focused research teams and are taught to make original contributions of interest to the scientific community. In addition to entering national competitions, the students are encouraged to publish in refereed scientific journals and to present their results at national conferences.   Students can continue during the academic year in the Mentor Program, which allows them to plan a research schedule with a faculty mentor throughout the year. The students have consistently won recognition for their research through national competitions ( LISEF,  NYCSEF,  NYSSEF,  ISEF), published in refereed journals, been awarded patents, inducted into the National Young Inventor's Hall of Fame.", featured: false),
//            Program(name: "Minority Introduction to Engineering and Science (MITES)", website: "oeop.mit.edu/programs/mites", location: ["Massachussets Institute of Technology"], country: Country.US , site: Site.Residential, creditsGiven: false, length: 6, date: Date(start_day: 21, start_month: 6, end_day: 3, end_month: 7), grade: [11], internationalAllowed: false, cost: 0, needBasedAid: false, Subject: Subject(engineering: true, physical_sciences: true, mathematics: true, computer_science: true), selectivity: true, entranceTest: false, entranceRequirements: [true, true, true, true, true, true, false, true], thresholdSAT: 1500, thresholdGPA: 3.5, description: "Minority Introduction to Engineering and Science (MITES) is a rigorous six-week residential academic enrichment program for rising high school seniors – many of whom come from underrepresented or underserved communities – who have a strong academic record and are interested in studying and exploring careers in science and engineering.  This national program stresses the value and reward of pursuing advanced technical degrees and careers while developing the skills necessary to achieve success in science and engineering. The programs empower highly-motivated scholars with the knowledge, confidence, and community necessary to pursue their passions for STEM at the nation’s top colleges and beyond.", featured: false),
            Program(name: "Research in Science & Engineering (RISE)", website: "bu.edu/summer/high-school-programs/rise-internship-practicum", location: ["Boston University"], country: Country.US, site: Site.Residential, creditsGiven: false, length: 6, date: Date(start_day: 3, start_month: 7, end_day: 12, end_month: 8), grade: [10], internationalAllowed: false, cost: 8580, needBasedAid: true, Subject: Subject(engineering: true, physical_sciences: true, mathematics: true, computer_science: true), selectivity: true, entranceTest: false, entranceRequirements: [true, true, true, false, false, false, true, false], thresholdSAT: 1500, thresholdGPA: 3.5, description: "RISE is a six-week program for high school seniors. The students spend six weeks at BU conducting university laboratory research with some of the nation’s brightest scientific minds while advancing their STEM knowledge and skills. The Internship track of the program involves spendind 40 hours each week working on research projects designed to help acquire valuable technical and analytical skills while developing insight into the scientific process. The Practicum track include two-hour lecture from the instructor and four hours of group research. The experiments are designed to demonstrate procedures that are representative of university laboratory research in computational neurobiology. ", featured: true),
            Program(name: "High School Honors Science, Math and Engineering Program", website: "https://education.msu.edu/hshsp/", location: ["Michigan State University"], country: Country.US, site: Site.Residential, creditsGiven: false, length: 7, date: Date(start_day: 21, start_month: 6, end_day: 8, end_month: 8), grade: [11], internationalAllowed: false, cost: 3800, needBasedAid: true, Subject: Subject(engineering: true, physical_sciences: true, mathematics: true, computer_science: true), selectivity: true, entranceTest: false, entranceRequirements: [true, true, true, true, true, true, true, false], thresholdSAT: 1500, thresholdGPA: 3.5, description: "The Michigan State University High School Honors  Science/Engineering/Mathematics Program (HSHSP) is a seven-week, intensive summer research program designed for motivated high school juniors with a keen interest in science, math or engineering and the ability to work independently and responsibly from across the United States who wish to gain more experience conducting research while living on the campus of a major research-intensive university.  Students are able to undertake detailed, focused investigation of challenging problems and to participate in many dimensions of the research process. Founded in 1958, the HSHSP is the oldest, non-credit enrichment program sponsored by the Department of Teacher Education of Michigan State University.", featured: false),
            Program(name: "Simons Summer Research Program", website: "stonybrook.edu/commcms/simons", location: ["Stony Brooks University"], country: Country.US, site: Site.Both, creditsGiven: false, length: 5, date: Date(start_day: 27, start_month: 6, end_day: 29, end_month: 7), grade: [11], internationalAllowed: false, cost: 0, needBasedAid: false, Subject: Subject(engineering: true, physical_sciences: true, mathematics: true, computer_science: true), selectivity: true, entranceTest: false, entranceRequirements: [true, true, true, false, false, false, true, false], thresholdSAT: 1500, thresholdGPA: 3.5, description: "The Simons Summer Research Program is a national, competitive summer research program for 11th grade students. The program gives academically talented, motivated high school students the opportunity to engage in hands-on research in science, math or engineering at Stony Brook University. Simons Fellows work with distinguished faculty mentors, learn laboratory techniques and tools, become part of active research teams, and experience life at a research university.  Simons Fellows are matched with Stony Brook faculty mentors, join a research group or team, and assume responsibility for a project. The Simons Fellows conclude their apprenticeship by producing a written research abstract and a research poster.", featured: false),
            Program(name: "Summer Academy for Math and Science", website: "cmu.edu/pre-college/academic-programs/sams.html", location: ["Carnegie Mellon University"], country: Country.US, site: Site.Residential, creditsGiven: false, length: 4, date: Date(start_day: 2, start_month: 7, end_day: 30, end_month: 7), grade: [11], internationalAllowed: false, cost: 0, needBasedAid: false, Subject: Subject(engineering: false, physical_sciences: true, mathematics: true, computer_science: false), selectivity: true, entranceTest: false, entranceRequirements: [true, true, true, true, true, true, false, true], thresholdSAT: 1500, thresholdGPA: 3.5, description: "The Summer Academy for Math and Science (SAMS) provides opportunities for students from underrepresented communities to explore STEM-related fields.The program allows students to develop a deeper understanding of STEM via traditional classroom instruction, through hands-on projects, and sustained engagement with world-renowned faculty and skilled staff mentors.  Students will attend workshops, meet with alumni, students, university leaders, and finalize STEM-based projects. In addition to their academic experiences, students also have the opportunity to collaborate and develop meaningful relationships with peers from across the country. The program broadens students' understanding and access to opportunities made available through study in STEM and equips them with the knowledge, skills, and dispositions to be successful STEM scholars. ", featured: true),
            Program(name: "HKUST Summer Institite", website: "summer.ust.hk", location: ["Hong Kong University of Science and Technology (HKUST)"], country: Country.HongKong, site: Site.Online, creditsGiven: false, length: 2, date: Date(start_day: 3, start_month: 8, end_day: 12, end_month: 8), grade: [10, 11], internationalAllowed: true, cost: 525, needBasedAid: false, Subject: Subject(engineering: true, physical_sciences: true, mathematics: false, computer_science: true), selectivity: true, entranceTest: false, entranceRequirements: [false, false, true, false, false, false, false, false], thresholdSAT: 1500, thresholdGPA: 3.5, description: "This program is conducted by Hong Kong Institute of Science and Technology. It offers various courses in Science and Engineering to secondary school students. Currently, the courses are conducted online through Zoom.It is open to students across the world.", featured: false),
            Program(name: "Pre University Summer School for International High School Students", website: "ucl.ac.uk/languages-international-education/short-summer-courses/pre-university-summer-school", location: ["University College London"], country: Country.UK, site: Site.Residential, creditsGiven: true, length: 2, date: Date(start_day: 25, start_month: 7, end_day: 5, end_month: 8), grade: [9, 10, 11], internationalAllowed: true, cost: 5500, needBasedAid: false, Subject: Subject(engineering: true, physical_sciences: true, mathematics: false, computer_science: false), selectivity: true, entranceTest: false, entranceRequirements: [true, false, true, false, false, false, true, true], thresholdSAT: 1500, thresholdGPA: 3.5, description: "The UCL Pre-University Summer School for International High School Students is a unique two-week residential course for students who want to experience life at one of the world's leading universities in the heart of London. The academic challenges, combined with a full programme of social activities, offer an exciting experience for summer. The UCL Pre-University Summer School is open to high-achieving 16 and 17 year old students who want to study a range of disciplines in the sciences, arts and humanities; learn how to conduct a research project at a world leading university; and experience student life at a global top 10 university in central London during the summer.", featured: false),
            Program(name: "Future Global Leaders", website: "extendedlearning.ubc.ca", location: ["University of British Columbia"], country: Country.Canada, site: Site.Both, creditsGiven: false, length: 2, date: Date(start_day: 11, start_month: 7, end_day: 22, end_month: 7), grade: [10, 11], internationalAllowed: true, cost: 4250, needBasedAid: false, Subject: Subject(engineering: true, physical_sciences: true, mathematics: false, computer_science: true), selectivity: true, entranceTest: false, entranceRequirements: [false, false, true, false, false, false, false, false], thresholdSAT: 1500, thresholdGPA: 3.5, description: "UBC Future Global Leaders is a pre-university program for high school students ages 15-18  who have completed grade 10 or equivalent that attracts ambitious, motivated students from across Canada and around the world. All courses are taught by UBC professors and instructors. The two-week on-campus program takes place in July and August and online courses are offered year-round. The recommended score is 78% average / 3.5 GPA / B average / IB 5 or higher and IELTS of 6.0 / TOEFL 80 or higher (or equivalent) for English language learners.", featured: false)
        ]
}

extension Program {
    static let someBoolean1 = false
    static let someBoolean2 = true
    static let double1 = 0.0
    static let double2 = 10.0
    static let double3 = 10000.00
    static let someString = "10"
    
    static func statsArray (satTaken: Bool, satScore: Double, GPA: Double, mathExamTaken: Bool, mathExamExcelled: Bool, scienceExamTaken: Bool, scienceExamExcelled: Bool, scienceProjectCompleted: Bool, scienceProjectAwarded: Bool, researchPaperWritten: Bool, researchPaperPublished: Bool, goodRecommendation: Bool, ECAparticipation: Bool) -> [Double] {
        var x: [Double] = [0, 0, 0, 0, 0, 0, 0, 0]
        
        if goodRecommendation {x[0] = 1}
        if satTaken {x[1] = (satScore - 400) / 1200} else {x[1] = 0}
        x[2] = GPA / 4
        if mathExamTaken {
            x[3] += 0.5
            if mathExamExcelled {x[3] += 0.5}
        }
        if scienceExamTaken {
            x[4] += 0.5
            if scienceExamExcelled {x[34] += 0.5}
        }
        if scienceProjectCompleted {
            x[5] += 0.5
            if scienceProjectAwarded {x[5] += 0.5}
        }
        if researchPaperWritten {
            x[6] += 0.5
            if researchPaperPublished {x[6] += 0.5}
        }
        if ECAparticipation {x[7] = 1}
        
        return x
    }
    
    func generateChance (studentStats: [Double]) -> Double {
        var sum: Double = 0
        for i in 0...7 {
            sum += (weightages[i] * studentStats[i])
        }
        return sum*100
    }
}
